### ISSUE TITLE
Any chance for python?

### ISSUE THREAD

**Issue by airmonitor** [megaproaktiv/cdk2d2#1]
Hey.

Thx for sharing your project.
Looks very interesting!

I'm wondering if you consider releasing also a python module?

Regards
Tom.

**Comment by megaproaktiv** [comment]
Absolutely. Just a time issue.
But you can use it with python CDK right away because the modules are just syntactic sugar:
See this example in python/cdk
[`https://github.com/megaproaktiv/cdk2d2-examples/tree/main/python/api-sqs-lambda`](https://github.com/megaproaktiv/cdk2d2-examples/tree/main/python/api-sqs-lambda)
